apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: aiven-kafka
spec:
  itemPath: "vaults/aks-alpha-vault/items/aiven-kafka"
---
apiVersion: "fintlabs.no/v1alpha1"
kind: NamOAuthClientApplicationResource
metadata:
  name: oauth2-client-flyt-file-service
  labels:
    app.kubernetes.io/name: oauth2-client-flyt-file-service
    app.kubernetes.io/instance: viken-no-oauth2-client-flyt-file-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: oauth-client
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
spec:
  grantTypes:
    - client_credentials
---
apiVersion: fintlabs.no/v1alpha1
kind: AzureBlobContainer
metadata:
  name: abs-flyt-file-service
  labels:
    app.kubernetes.io/name: flyt-file-service
    app.kubernetes.io/instance: viken-no-flyt-file-service
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: azure-blob-storage
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: fint-flyt-file-service
  name: fint-flyt-file-service
spec:
  ports:
    - port: 8080
  type: ClusterIP
  selector:
    io.kompose.service: fint-flyt-file-service
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-fint-flyt-file-service-internal
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/auth-signin: https://$host/oauth2/start?rd=$escaped_request_uri
    nginx.ingress.kubernetes.io/auth-url: https://$host/oauth2/auth
    nginx.ingress.kubernetes.io/configuration-snippet: |
      auth_request_set $token $upstream_http_authorization;
      proxy_set_header Authorization $token;
      proxy_pass_header Authorization;
spec:
  rules:
    - host: "viken-no-skjema.vigoiks.no"
      http:
        paths:
          - path: /api/intern/integrasjoner
            pathType: Prefix
            backend:
              service:
                name: fint-flyt-file-service
                port:
                  number: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    io.kompose.service: fint-flyt-file-service
  name: fint-flyt-file-service
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      io.kompose.service: fint-flyt-file-service
  template:
    metadata:
      labels:
        io.kompose.service: fint-flyt-file-service
    spec:
      restartPolicy: Always
      volumes:
        - name: credentials
          secret:
            secretName: aiven-kafka-certificates
      containers:
        - image: fintlabsacr.azurecr.io/fint-flyt-file-service:dummy
          name: fint-flyt-file-service
          volumeMounts:
            - name: credentials
              mountPath: /credentials
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1"
            requests:
              memory: "512Mi"
              cpu: "100m"
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aiven-kafka
            - secretRef:
                name: oauth2-client-flyt-file-service
            - secretRef:
                name: abs-flyt-file-service
          env:
            - { name: TZ, value: Europe/Oslo }
            - { name: JAVA_TOOL_OPTIONS, value: '-XX:+ExitOnOutOfMemoryError -Xmx1840M' }
            - { name: fint.org-id, value: 'viken.no' }
