fint:
  application-id: fint-flyt-file-service

novari:
  flyt:
    file-service:
      max-request-size: 1024MB
    web-resource-server:
      security:
        api:
          internal-client:
            authorized-client-ids: ${fint.sso.client-id}

server:
  error:
    include-message: always
  tomcat:
    max-swallow-size: ${novari.flyt.file-service.max-request-size}
    max-http-form-post-size: ${novari.flyt.file-service.max-request-size}

spring:
  http:
    codecs:
      max-in-memory-size: ${novari.flyt.file-service.max-request-size}
  profiles:
    include:
      - flyt-kafka
      - flyt-logging
      - flyt-web-resource-server
  servlet:
    multipart:
      max-file-size: ${novari.flyt.file-service.max-request-size}
      max-request-size: ${novari.flyt.file-service.max-request-size}

  output:
    ansi:
      enabled: always
