apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: viken-no
resources:
  - ../../../base
patchesStrategicMerge:
  - config-map.yaml
commonLabels:
  app.kubernetes.io/name: fint-flyt-file-service
  app.kubernetes.io/instance: fint-flyt-file-service_viken-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-flyt
  fintlabs.no/team: flyt
  fintlabs.no/org-id: viken.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/routes/0/match"
        value: "Host(`flyt.vigoiks.no`) && PathPrefix(`/alpha/viken-no/api/intern-klient/filer`)"
    target:
      kind: IngressRoute
      name: fint-flyt-file-service
  - patch: |-
      - op: replace
        path: "/spec/acls/0/topic"
        value: "viken-no.flyt.*"
    target:
      kind: KafkaUserAndAcl
      name: fint-flyt-file-service

