apiVersion: fintlabs.no/v1alpha1
kind: Application
metadata:
  name: fint-flyt-file-service
  namespace: fintlabs-no
  labels:
    app.kubernetes.io/name: fint-flyt-file-service
    app.kubernetes.io/instance: fint-flyt-file-service_fintlabs_no
    app.kubernetes.io/version: latest
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: fint-flyt
    fintlabs.no/team: flyt
    fintlabs.no/org-id: fintlabs.no
spec:
  port: 8080
  imagePullPolicy: Always
  orgId: fintlabs.no
  image: ghcr.io/fintlabs/fint-flyt-file-service:sha-0000000
  kafka:
    enabled: true
    acls:
      - permission: admin
        topic: 'no-permission'
  env:
    - name: JAVA_TOOL_OPTIONS
      value: '-XX:+ExitOnOutOfMemoryError -Xmx768M -Xms512M'
  envFrom:
    - secretRef:
        name: fint-flyt-file-service-azure-blob-storage
    - secretRef:
        name: fint-flyt-file-oauth2-client
  resources:
    limits:
      memory: "1024Mi"
      cpu: "150m"
    requests:
      memory: "512Mi"
      cpu: "50m"
  restartPolicy: Always
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate: { maxSurge: 1, maxUnavailable: 0 }